version: "3.7"

services:

  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgresql_db
    command: sh -c './wait-for postgresql_db:5432 -- npm start'

  postgresql_db:
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "ehwaz"
